# Generated by Django 4.1.5 on 2024-02-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_rename_locality_upload_city_upload_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="size_range",
            field=models.TextField(blank=True, null=True),
        ),
    ]
